### ISSUE TITLE
The code is not working

### ISSUE THREAD

**Issue by mkassir95** [Chetan11-dev/stanzajs-ejabberd-example#2]
Hello,

I run the same code, but the request in the postman is not respoding knowing that the ejabberd server  is working

![image](https://user-images.githubusercontent.com/72728047/207391516-939dcf5b-1213-45cb-8456-4401f1fd2477.png)

![image](https://user-images.githubusercontent.com/72728047/207391715-2d987527-7bf6-40b1-9786-26aedccbb05b.png)

**Comment by alexander-manariotis** [comment]
In the ejabberd.yml file make sure to comment out:
db_type: sql

By default Ejabberd uses a non SQL database, this option assumes you have set a separate one up.

By commenting it out your requests will work.

**Comment by idubi** [comment]
for me it worked for both 
if you run on windows or mac , make sure the **network_mode: 'host**' is remarked or deleted in docker-compose.yml

**Comment by Chetan11-dev** [comment]
@idubi Thanks, I updated code with your suggestions and this problem should not occur.
